### ISSUE TITLE
Schedule and Task CRUD

### ISSUE THREAD

**Issue by amberemeny** [amberemeny/plantabse-react#4]
Schedule CRUD should work as CRUD typically should but on creation, tasks are created based on the start date, end date and interval in day(s). Tasks then have a Boolean completion field so that completed tasks can be logged. 

**Schedule CRUD:**
- [ ] Index Schedules - Schedules listed in Plant View.
- [ ] View Schedule - View all Tasks in a Schedule via a view or dialog.
- [ ] Create Schedule - Generates tasked based on fields. 
- [ ] Edit Schedule - _Suggestion: on Edit, remove all uncompleted future tasks, and regenerate new tasks based on Schedule fields._
- [ ] Remove Schedule - Deletes all future uncompleted tasks. 
`Serializer for Schedule onDelete - Delete Tasks if completed === false`

**Task CRUD:**
- [ ] Index Tasks - Should be visible on the Schedule View.
- [ ] View Task - There is not a need for an individual view for a Task.
- [ ] Create Task - Automatically generated on Schedule create.
- [ ] Edit Task - Individual Tasks not able to be edited, only the parent schedule.
- [ ] Delete Task - Tasks should be deleted through a change in Schedule or Schedule Deletion.

**Possible Views:**
- Schedule List
- View Schedule and list Tasks in to-do form.
- *View Task Completion History?*
- Edit Schedule
